[librispeech-alignment-BIES-100]
train_file=./data/LibriSpeech-Alignment-BIES/train-clean-100.csv
val_file=./data/LibriSpeech-Alignment-BIES/dev-clean.csv
test_file=./data/LibriSpeech-Alignment-BIES/test-clean.csv
label_csv=./data/LibriSpeech-Alignment-BIES/class.csv
class_num=47
sound_length=1

[librispeech-alignment-BIES-360]
train_file=./data/LibriSpeech-Alignment-BIES/train-clean-360.csv
val_file=./data/LibriSpeech-Alignment-BIES/dev-clean.csv
test_file=./data/LibriSpeech-Alignment-BIES/test-clean.csv
label_csv=./data/LibriSpeech-Alignment-BIES/class.csv
class_num=47
sound_length=1

[librispeech-alignment-BIES-500]
train_file=./data/LibriSpeech-Alignment-BIES/train-other-500.csv
val_file=./data/LibriSpeech-Alignment-BIES/dev-clean.csv
test_file=./data/LibriSpeech-Alignment-BIES/test-clean.csv
label_csv=./data/LibriSpeech-Alignment-BIES/class.csv
class_num=47
sound_length=1

