[speechcommand-v2]
train_file=./data/speechcommand-v2/train.json
val_file=./data/speechcommand-v2/eval.json
test_file=./data/speechcommand-v2/test.json
label_csv=./data/speechcommand-v2/class.csv
class_num=35
sound_length=1
