[audioset]
train_file=./data/audioset/unbalanced_train.json
val_file=./data/audioset/eval.json
label_csv=./data/audioset/class.csv
class_num=527
sound_length=10

[audioset-bal]
train_file=./data/audioset/balanced_train.json
val_file=./data/audioset/eval.json
label_csv=./data/audioset/class.csv
class_num=527
sound_length=10

[esc-50]
train_file=./data/esc-50/esc_train_data_1.json
val_file=./data/esc-50/esc_eval_data_1.json
label_csv=./data/esc-50/class.csv
class_num=50
sound_length=5

[huiruisyl]
train_file=./data/huiruisyl/train.json
val_file=./data/huiruisyl/eval.json
label_csv=./data/huiruisyl/class.csv
class_num=14
sound_length=5

[speechcommand-v2]
train_file=./data/speedcommand-v2/train.json
val_file=./data/speedcommand-v2/eval.json
label_csv=./data/speedcommand-v2/class.csv
class_num=35
sound_length=1

[speechcommand-v1]
train_file=./data/speechcommand-v1/train.json
val_file=./data/speechcommand-v1/eval.json
label_csv=./data/speechcommand-v1/class.csv
class_num=31
sound_length=1

[librispeech-alignment-word-360]
train_file=./data/LibriSpeech-Alignments-Word/train-clean-360.json
val_file=./data/LibriSpeech-Alignments-Word/dev-clean.json
label_csv=/dev/null
class_num=39
sound_length=1

[librispeech-alignment-word-100]
train_file=./data/LibriSpeech-Alignments-Word/train-clean-100.json
val_file=./data/LibriSpeech-Alignments-Word/dev-clean.json
label_csv=/dev/null
class_num=39
sound_length=1

[librispeech-alignment-strong-labels]
train_file=./data/LibriSpeech-Alignment-Strong-Labels/train-clean-100.csv
val_file=./data/LibriSpeech-Alignment-Strong-Labels/dev-clean.csv
label_csv=./data/LibriSpeech-Alignment-Strong-Labels/class.csv
class_num=43
sound_length=1

[librispeech-alignment-BIES]
train_file=./data/LibriSpeech-ALignment-BIES/train-clean-100.csv
val_file=./data/LibriSpeech-ALignment-BIES/dev-clean.csv
label_csv=./data/LibriSpeech-ALignment-BIES/class.csv
class_num=47
sound_length=1

